name: Crawl Jewish News

on: 
   workflow_dispatch:
   schedule:
     - cron: "0 6 * * *"  # Daily at 6 AM UTC

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr 
            any::jsonlite
            any::xml2
            any::lubridate

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main_folder
          ref: main

      - name: Scrape news RSS feeds
        working-directory: ./main_folder
        run: |
          Rscript crawl-news.R

      - name: Commit results main branch 
        working-directory: ./main_folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m "News data updated" || exit 0
          git push origin
